taskmanager/main/urls.py
from django.urls import path
from . import views
from random import randint

urlpatterns = [
    ###___Local___###
    path('', views.index, name='home'),
    path('my-board/', views.index, name='home'),
    path('my-board/create-notes/', views.create.as_view(), name='create'),
    path('my-board/<int:pk>/views/',views.view_note, name='views-notes'),
    path('my-board/<int:pk>/views/delete',views.delete_note, name='delete-notes'),

    ###___Server___###
    path('server-board/', views.index_server, name='server-board-view'),
    path('server-board/create-notes/', views.server_create.as_view(), name='server-create'),
    path(f'server-board/account/<int:pk>/views/',views.server_account_view.as_view(), name='server-account-views'),
    path(f'server-board/<int:pk>/views/',views.server_view_note.as_view(), name='server-views-notes'),
    path('server-board/<int:pk>/views/delete/',views.server_delete_note.as_view(), name='server-delete-notes'),
    path(f'server-board/<int:pk>/views/reactions/',views.server_reaction_view, name='server-views-reactions'),


    ###___Account___###
    path('account/login/', views.LoginUser.as_view(), name='login-page'),
    path('account/register/', views.RegisterUser.as_view(), name='regist-page'),
    path('account/logout/', views.LogoutUser.as_view(), name='logout-page'),
    path('account/profile/', views.ProfileUser.as_view(), name='profile-page'),
    path('account/profile/<int:pk>/edit/', views.EditProfil.as_view(), name='profile-edit-page'),

]

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

taskmanager/main/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Task(models.Model):
    role = (('red', 'Red'),
            ('yellow', 'Yellow'),
            ('blue','Blue'),
            ('green','Green')
            )
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Owners notes", blank=True, null=True)
    title = models.CharField('Name', max_length=16)
    task = models.TextField('Task',max_length=200)
    time_create = models.DateTimeField(auto_now_add=True)
    crossed_out = models.BooleanField ('crossed', default=False)
    color = models.CharField(max_length=10, choices=role, default='red')

    role = (('red','Red'),('yellow','Yellow'))
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/my-board/'

    class Meta:
        verbose_name_plural = 'My board'

class Server_Board(models.Model):
    role = (('red', 'Red'),
            ('yellow', 'Yellow'),
            ('blue','Blue'),
            ('green','Green')
            )
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Owners notes", blank=True, null=True)
    title = models.CharField('Name', max_length=16)
    task = models.TextField('Task',max_length=200)
    time_create = models.DateTimeField(auto_now_add=True)
    crossed_out = models.BooleanField ('crossed', default=False)
    reaction_count_in_post = models.ManyToManyField(User,related_name='reaction_count_in_post')
    color = models.CharField(max_length=10, choices=role, default='red')

    role = (('red','Red'),('yellow','Yellow'))

    def total_likes(self):
        return self.reaction_count_in_post.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/server-board/'

    class Meta:
        verbose_name_plural = 'Server board'

# class CustomUser(AbstractUser):
#     avatar_url = models.CharField('avatar_url',max_length= 100, default="https://i.imgur.com/BoZwIXW.png")
# #     bio = models.TextField('bio',max_length=200)
# #     reaction_count = models.CharField('avatar_url',max_length= 100)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    avatar_url = models.CharField('avatar_url',null=True, max_length=100, default="https://i.imgur.com/BoZwIXW.png")
    bio = models.TextField('bio',max_length=300,null=True, default="")
    reaction_count = models.CharField('reaction_count',null=True,max_length= 100, default=0)
    activation_email = models.BooleanField('activat', default=False, null=True)


    def __unicode__(self):
        return self.user

    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'

    @receiver(post_save, sender=User)
    def create_or_update_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

        instance.userprofile.save()

taskmanager/main/forms.py
from .models import Task, Server_Board, UserProfile
from django.forms import  ModelForm, TextInput, Textarea,EmailInput, PasswordInput
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms

###___Local___###
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "task","crossed_out","color"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'input-title',
                'placeholder': ' Enter name',
            }),
            "task": Textarea(attrs={
                'class': 'input-notes',
                'placeholder': ' Enter text',
                'col': "8",
                'rows': "8",
            }),
        }

###___Server___###
class ServerForm(ModelForm):
    class Meta:
        model = Server_Board
        fields = ["title", "task","crossed_out","color"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'input-title',
                'placeholder': ' Enter name',
            }),
            "task": Textarea(attrs={
                'class': 'input-notes',
                'placeholder': ' Enter text',
                'col': "8",
                'rows': "8",
            }),
        }

###___Account___###
class AuthUserForm(AuthenticationForm, ModelForm):
    class Meta():
        model = User
        fields = ("username", "password")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields["password"].widget.attrs['placeholder'] = "Password"
            self.fields["username"].widget.attrs['placeholder'] = "User name"

class RegisterUserForm(ModelForm):
    class Meta():
        model = User
        fields = ("username", "password","email")
        widgets = {
            "username": TextInput(attrs={

                'class': "form-control",
                'placeholder': "User name"
            }),
            "password": PasswordInput(attrs={

                'class': "form-control",
                'placeholder': "Password"
            }),
            "email": EmailInput(attrs={

                'class': "form-control",
                'placeholder': "Email"
            }),
        }
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class EditProfileForm(ModelForm):
    class Meta():
        model = UserProfile
        fields = ("bio",)
        widgets = {
            "bio": Textarea(attrs={
                'class': 'me-3 py-2 text-dark text-decoration-none bio-area',
                'placeholder': ' Enter text',

            }),
        }

taskmanager/main/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task, Server_Board, UserProfile
from .forms import TaskForm, ServerForm,EditProfileForm, AuthUserForm, RegisterUserForm
from django.views.generic import DeleteView, UpdateView, DetailView, CreateView, ListView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, Http404


###____Local____###

def index(request):
    tasks = Task.objects.order_by('-id')
    return render(request, 'main/Local/my-board.html', {'title': 'Главная', 'tasks':tasks })

def delete_note (request, pk):
    error = ''
    post = get_object_or_404(Task, pk=pk)
    tasks = Task.objects.order_by('-id')

    if request.method == 'POST' and "succes-delete-btn" in request.POST:

        Task.objects.get(pk=pk).delete()

        return redirect('home')

    if request.method == 'POST' and "cancel-delete-btn" in request.POST:
        return redirect(f'/my-board/{pk}/views')

    form = TaskForm()
    context = {
        'post': post,
        'form': form,
        'tasks': tasks,
        'error': error
    }
    return render(request, 'main/Local/Delete_Notes.html', context)

def view_note(request, pk):
    error = ''
    post = get_object_or_404(Task, pk=pk)
    tasks = Task.objects.order_by('-id')


    form = TaskForm()
    context = {
        'post': post,
        'form': form,
        'tasks': tasks,
        'error' :error
    }
    return render(request, 'main/Local/Notes_view.html', context)

class create(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login-page')
    model = Task
    template_name = 'main/Local/Create.html'
    form_class = TaskForm
    success_url = reverse_lazy('home')
    def get_context_data(self, **kwargs):
        kwargs['list_notes'] = Task.objects.order_by('-id')
        return super().get_context_data(**kwargs)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


###____Server____###

class server_view_note(DetailView):
    model = Server_Board
    template_name = 'main/Server/server-view.html'
    context_object_name = 'post'


    def get_context_data(self, **kwargs):
        context = super(server_view_note, self).get_context_data(**kwargs)
        stuff = get_object_or_404(Server_Board, id=self.kwargs['pk'])
        total_reactions = stuff.total_likes()
        context['users'] = User.objects.all()
        context['list_notes'] = Server_Board.objects.order_by('-id')
        context['total_reactions'] = total_reactions
        return context


def index_server(request):
    tasks = Server_Board.objects.order_by('-id')

    return render(request, 'main/Server/server-board.html', {'title': 'Главная', 'tasks':tasks,})

class server_create(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login-page')
    model = Server_Board
    template_name = 'main/Server/server-create.html'
    form_class = ServerForm
    success_url = reverse_lazy('server-board-view')
    def get_context_data(self, **kwargs):
        kwargs['list_notes'] = Server_Board.objects.order_by('-id')
        return super().get_context_data(**kwargs)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class server_delete_note(LoginRequiredMixin ,DeleteView):
    model = Server_Board
    template_name = 'main/Server/server-delete.html'
    success_url = reverse_lazy('server-board-view')
    context_object_name = 'post'
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(self.object.author)
        print(self.request.user)
        if self.request.user != self.object.author:
            return self.handle_no_permission()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        kwargs['list_notes'] = Server_Board.objects.order_by('-id')
        return super().get_context_data(**kwargs)

class server_account_view(DetailView):
    model = User
    template_name = 'main/Server/server-account-view.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(server_account_view, self).get_context_data(**kwargs)
        print(self.object)
        num_post = Server_Board.objects.filter(author=self.object)
        reactions_num = 0
        for post in num_post:
            stuff = get_object_or_404(Server_Board, id=post.pk)
            total_reactions = stuff.total_likes()
            reactions_num = total_reactions + reactions_num
        context['all_count_reactions'] = reactions_num
        context['list_notes'] = Server_Board.objects.order_by('-id')
        return context

def server_reaction_view(request, pk):
    notes = get_object_or_404(Server_Board, id=request.POST.get('notes_id'))
    notes.reaction_count_in_post.add(request.user)
    return HttpResponseRedirect(reverse('server-views-notes', args=[str(pk)]))



###____Login____###

class LogoutUser(LogoutView):
    next_page = 'home'

class LoginUser(LoginView):
    template_name = 'main/Account/Login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('home')
    def get_success_url(self):
        return self.success_url

class ProfileUser(ListView):
    model = User
    template_name = 'main/Account/Account-cabinet.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(ProfileUser, self).get_context_data(**kwargs)
        num_post = Server_Board.objects.filter(author=self.request.user)
        reactions_num = 0
        for post in num_post:
            stuff = get_object_or_404(Server_Board, id=post.pk)
            total_reactions = stuff.total_likes()
            reactions_num = total_reactions + reactions_num
        context['all_count_reactions'] = reactions_num
        context['list_notes'] = Server_Board.objects.order_by('-id')
        return context

class EditProfil(UpdateView):
    model = UserProfile
    form_class = EditProfileForm
    template_name = 'main/Account/Account-edit.html'
    success_url = reverse_lazy('profile-page')
    def get_context_data(self, **kwargs):
        context = super(EditProfil, self).get_context_data(**kwargs)
        num_post = Server_Board.objects.filter(author=self.request.user)
        reactions_num = 0
        for post in num_post:
            stuff = get_object_or_404(Server_Board, id=post.pk)
            total_reactions = stuff.total_likes()
            reactions_num = total_reactions + reactions_num
        context['all_count_reactions'] = reactions_num
        context['list_notes'] = Server_Board.objects.order_by('-id')
        return context

class RegisterUser(CreateView):
    model = User
    template_name = 'main/Account/Register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        aut_user = authenticate(username=username, password=password)

        login(self.request,aut_user)
        return form_valid


###____Other____###

taskmanager/main/templates/main/Server/server-account-view.html
{% extends 'main/base.html'%}

{% block title%}
Account
{% endblock %}



{% block head%}
<style type="text/css">

    .coupon-view {

       margin: 0 auto; /* Center the coupon */
       max-width: 800px;
       -o-transform:rotate(-3deg);
       -webkit-transform:rotate(-3deg);
       -moz-transform:rotate(-3deg);
       position:relative;
       top:5px;
       /* Firefox */
       -moz-box-shadow:10px 10px 12px rgba(33,33,33,1);
       /* Safari+Chrome */
       -webkit-box-shadow: 10px 10px 12px rgba(33,33,33,.7);
       /* Opera */
       box-shadow: 0px 0px 25px rgba(33,33,33,.7);
    }

    .crap-img{
        margin: 0 right;
        width: 10%;
        position: absolute;
        right: -5px;
        top: -7px;

    }
    .crap-img-view{
        margin: 0 right;
        width: 10%;
        position: absolute;
        right: -5px;
        top: -7px;
    }


   .containers {
        padding: 2px 16px;
   }

    .view-place{

        z-index: 100;
        position: absolute;
        bottom: 150px;
        right:170px;
        width:320px;

    }

    textarea::-webkit-scrollbar {
        width: 0.5em;

    }

    textarea::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    }

    textarea::-webkit-scrollbar-thumb {
        background-color: darkgrey;
        outline: 1px solid slategrey;
    }

   .view-containers {
        padding: 2px 16px;
   }

   .account-img-preview{
        width: 25px;
        height: 25px;
        border-radius: 30px;

   }

   .reaction-img{
        width: 25px;
        height: 25px;
        margin-right: 5px;
        margin-bottom: 5px;
   }
   .info-block{
        float: left;
        width: 360px;

   }
   .info-text{
        margin-bottom: 0px;
        font-size: 18px;
   }
   .bio-area{
        height: 150px;
        width: 500px;
        resize: none;
        outline: 0;
        border: 0px solid black;
        float: left;


   }
    .coupon:hover, .coupon:focus{
        -moz-box-shadow:10px 10px 7px rgba(0,0,0,.7);
        -webkit-box-shadow: 10px 10px 7px rgba(0,0,0,.7);
        box-shadow:10px 10px 7px rgba(0,0,0,.7);
        -webkit-transform: scale(1.05);
        -moz-transform: scale(1.05);
        -o-transform: scale(1.05);
        position:relative;
        z-index:5;
    }
   .coupon {

       margin: 0 auto; /* Center the coupon */
       max-width: 800px;
       -o-transform:rotate(-3deg);
       -webkit-transform:rotate(-3deg);
       -moz-transform:rotate(-3deg);
       position:relative;
       top:5px;

       /* Firefox */
       -moz-box-shadow:5px 5px 7px rgba(33,33,33,1);
       /* Safari+Chrome */
       -webkit-box-shadow: 5px 5px 7px rgba(33,33,33,.7);
       /* Opera */
       box-shadow: 5px 5px 7px rgba(33,33,33,.7);
   }
    .crap-img{
        margin: 0 right;
        width: 10%;
        position: absolute;
        right: -5px;
        top: -7px;

    }
    .containers-title{
    padding: 0px 16px;
   }

   .containers {
        padding: 2px 16px;
   }

   .expire {
       font-family:"Neucha",serif;
       color: gray;
       font-size:80%;
   }
   .block-img{
        padding: 0px 0px;
        width: 150px;

   }
   .reaction-img-notes{
        width: 10px;
        height: 10px;
        margin-right: 1px;
        margin-bottom: 1px;
   }

 </style>
{% endblock %}



{% block content%}
<!--    Edit-->

<!--        reaction-avatar-user-->
    <div class="block-img">
        <img style="border-radius: 30px;" src="{{post.userprofile.avatar_url}}">

        <p class="me-3 py-2 text-dark text-decoration-none" >
            <img class="reaction-img" src="https://i.imgur.com/fgAIs12.png">
            <span style="font-size: 20px;">{{all_count_reactions}}</span>
        </p>
    </div>
<!--        user-date-->
    <div class="info-block">
        <p class="me-3 py-2 text-dark text-decoration-none info-text" >User name:{{post}}</p>
<!--        <p class="me-3 py-2 text-dark text-decoration-none info-text" >Email: {{user.email}}</p>-->
        <p class="me-3 py-2 text-dark text-decoration-none info-text">Date joined: {{post.date_joined}}</p>
    </div>
<!--        about-user-->
    <div style="width: 500px;">
        <textarea class="me-3 py-2 text-dark text-decoration-none bio-area" readonly>Bio: {{post.userprofile.bio}}</textarea>
    </div>

    <div>
        {% if list_notes %}

        {% for el in list_notes %}

            {% if post == el.author%}
            <div class="column">
                <div class="coupon" style="{% if el.color == 'red' %}
                                                background-color: #EF9F6B;
                                            {% endif %}

                                            {% if el.color == 'yellow' %}
                                                background-color:  #E3DA53;
                                            {% endif %}
                                            {% if el.color == 'blue' %}
                                                background-color: #6BBEE5;
                                            {% endif %}

                                            {% if el.color == 'green' %}
                                                background-color:  #8CE870;
                                            {% endif %}">
                    <img class="crap-img" src="https://i.imgur.com/kX19d4S.png">
                    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'server-views-notes' el.id%}">
                      <div class="containers-title" >

                          <h4 class="titel-notes">{{ el.title}}</h4>

                      </div>

                      <div class="containers">
                        <p class="text-notes">{{ el.task}}</p>
                        <p class="expire">
                            {{ post.author }}
                            {{ el.time_create }}
                            <img class="reaction-img-notes" src="https://i.imgur.com/fgAIs12.png">
                            {{el.reaction_count_in_post.count}}

                        </p>

                      </div>

                    </a>
                </div>
            </div>
            {% else %}

            {% endif %}
        {% endfor %}
        {% else %}
            <p> We don`t have notes </p>
        {% endif %}

    </div>
{% endblock %}

taskmanager/main/templates/main/Server/server-delete.html
{% extends 'main/base.html'%}

{% block title%}
Board
{% endblock %}

{% block head%}
<link  href="http://fonts.googleapis.com/css?family=Neucha&subset=cyrillic" rel="stylesheet" type="text/css" >
<style type="text/css">
    .titel-notes{
        font-size:150%;
        font-weight:bold;
        padding-bottom:10px;

    }
    .text-notes {
        font-family:"Neucha",serif;
        font-size:120%;


    }

    .coupon-delete {
        {% if post.color == 'red' %}
            background-color: #EF9F6B;
        {% endif %}

        {% if post.color == 'yellow' %}
            background-color:  #E3DA53;
        {% endif %}
        {% if post.color == 'blue' %}
            background-color: #6BBEE5;
        {% endif %}

        {% if post.color == 'green' %}
            background-color:  #8CE870;
        {% endif %}
       margin: 0 auto; /* Center the coupon */
       max-width: 800px;
       -o-transform:rotate(-3deg);
       -webkit-transform:rotate(-3deg);
       -moz-transform:rotate(-3deg);
       position:relative;
       top:5px;
       /* Firefox */
       -moz-box-shadow:10px 10px 12px rgba(33,33,33,1);
       /* Safari+Chrome */
       -webkit-box-shadow: 10px 10px 12px rgba(33,33,33,.7);
       /* Opera */
       box-shadow: 0px 0px 25px rgba(33,33,33,.7);
    }
    .coupon:hover, .coupon:focus{
        -moz-box-shadow:10px 10px 7px rgba(0,0,0,.7);
        -webkit-box-shadow: 10px 10px 7px rgba(0,0,0,.7);
        box-shadow:10px 10px 7px rgba(0,0,0,.7);
        -webkit-transform: scale(1.05);
        -moz-transform: scale(1.05);
        -o-transform: scale(1.05);
        position:relative;
        z-index:5;
    }
   .coupon {

       margin: 0 auto; /* Center the coupon */
       max-width: 800px;
       -o-transform:rotate(-3deg);
       -webkit-transform:rotate(-3deg);
       -moz-transform:rotate(-3deg);
       position:relative;
       top:5px;

       /* Firefox */
       -moz-box-shadow:5px 5px 7px rgba(33,33,33,1);
       /* Safari+Chrome */
       -webkit-box-shadow: 5px 5px 7px rgba(33,33,33,.7);
       /* Opera */
       box-shadow: 5px 5px 7px rgba(33,33,33,.7);
   }
    .crap-img{
        margin: 0 right;
        width: 10%;
        position: absolute;
        right: -5px;
        top: -7px;

    }
    .crap-img-delete{
        margin: 0 right;
        width: 10%;
        position: absolute;
        right: -5px;
        top: -7px;
    }
   .containers-title{
    padding: 0px 16px;
   }

   .containers {
        padding: 2px 16px;
   }

   .expire {
       font-family:"Neucha",serif;
       color: gray;
       font-size:80%;
   }
    .delete-place{

        z-index: 100;
        position: fixed;
        bottom: 35px;
        right:20px;
        width:300px;

    }
    .background-create{
        opacity: 0.3;
        width: 100%;

        background: #000000;
        margin: 0 auto;
    }

    .delete-containers-title{
    padding: 10px 16px;
   }
   .delete-title{
        {% if post.color == 'red' %}
            background-color: #EF9F6B;
        {% endif %}

        {% if post.color == 'yellow' %}
            background-color:  #E3DA53;
        {% endif %}
        {% if post.color == 'blue' %}
            background-color: #6BBEE5;
        {% endif %}

        {% if post.color == 'green' %}
            background-color:  #8CE870;
        {% endif %}

        outline: 0;
        border: 0px solid black;
        margin: 0 auto;
        font-size:150%;
        font-weight:bold;
        width:250px;
   }
   .delete-notes{
        {% if post.color == 'red' %}
            background-color: #EF9F6B;
        {% endif %}

        {% if post.color == 'yellow' %}
            background-color:  #E3DA53;
        {% endif %}
        {% if post.color == 'blue' %}
            background-color: #6BBEE5;
        {% endif %}

        {% if post.color == 'green' %}
            background-color:  #8CE870;
        {% endif %}

        resize: none;
        max-height: 250px;
        outline: 0;
        border: 0px solid black;
        font-family:"Neucha",serif;
        font-size:120%;

        width:250px;
   }

    textarea::-webkit-scrollbar {
        width: 0.5em;

    }

    textarea::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    }

    textarea::-webkit-scrollbar-thumb {
        background-color: darkgrey;
        outline: 1px solid slategrey;
    }

   .delete-containers {
        padding: 2px 16px;
   }
   .add-img{
        margin: 0 right;
        width: 55px;
        position: fixed;
        right: 30px;
        bottom: 25px;
   }
   .add-img:hover, .add-img:focus{
        -webkit-transform: scale(1.1);
   }
   .reaction-img{
        width: 10px;
        height: 10px;
        margin-right: 1px;
        margin-bottom: 1px;
   }
</style>

{% endblock %}

{% block content%}
    <h4>Questions</h4>
    <a href="{% url 'server-create'%}"><img  class="add-img"  src="https://i.imgur.com/Cazmill.png"></a>


    {% if list_notes %}

    {% for el in list_notes %}
        <div class="column">
            <div class="coupon" style="{% if el.color == 'red' %}
                                            background-color: #EF9F6B;
                                        {% endif %}

                                        {% if el.color == 'yellow' %}
                                            background-color:  #E3DA53;
                                        {% endif %}
                                        {% if el.color == 'blue' %}
                                            background-color: #6BBEE5;
                                        {% endif %}

                                        {% if el.color == 'green' %}
                                            background-color:  #8CE870;
                                        {% endif %}">
                <img class="crap-img" src="https://i.imgur.com/kX19d4S.png">
                <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'server-views-notes' el.id%}">
                  <div class="containers-title" >

                      <h4 class="titel-notes">{{ el.title}}</h4>

                  </div>

                  <div class="containers">
                    <p class="text-notes">{{ el.task}}</p>
                    <p class="expire">
                        {{ el.author }}
                        {{ el.time_create }}
                        <img class="reaction-img" src="https://i.imgur.com/fgAIs12.png">
                        {{el.reaction_count_in_post.count}}</p>

                  </div>

                </a>

            </div>
        </div>

    {% endfor %}
    {% else %}
        <p> We don`t have notes </p>
    {% endif %}
    <div class="background-create">

    </div>
    <div class="delete-place">
            <div class="coupon-delete">
                <a href="{% url 'server-views-notes' post.id%}"><img class="crap-img-delete" src="https://i.imgur.com/kX19d4S.png" ></a>
                <form method="post">

                    <div class="delete-containers">
                        <textarea class="delete-notes"  rows="9" id="id_task" style="padding: 30px 0px;" readonly>Are you sure you want to delete</textarea>
                        <span>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" name="succes-delete-btn" style="margin: 0 auto">Delete</button>

                        </span>
                    </div>
                </form><br>
            </div>
        </div>
{% endblock %}